### ISSUE TITLE
Support iOS with SwiftUSD

### ISSUE THREAD

**Issue by furby-tm** [wabiverse/SwiftUSD#4]
### What

SwiftUSD should work across **iOS** and **visionOS**, no different than the **macOS** platform.

**iOS** and **visionOS** both remain untested and unattempted for use in Swift packages. The theory is that there are few changes to be made, if any, then when building for **macOS**. The rationale is that the **Boost**, **Python**, and **MoltenVK** `*.xcframework` dependencies have already been built to be supportive of these platforms, but further testing is necessary to ensure this remains true. 

### Why

SwiftUSD is intended to be operating system agnostic, and fully supported across **Linux**, all Apple family devices (**macOS**, **visionOS**, **iOS**, **watchOS**, and **tvOS**), and **Microsoft Windows**.

<hr>

### Discussed in [Q&A](https://github.com/orgs/wabiverse/discussions/10)

<div type='discussions-op-text'>

<sup>Originally posted by **@SimonBenAnderson** December  4, 2023</sup>
Hi Wabiverse Team,

I was wondering if the SwiftUSD binding that you have work for the iOS environment?

As I have been looking for Swift OpenUSD bindings for an app

Thanks,
Simon
</div>

<hr>

**Comment by furby-tm** [comment]
Quick update, I believe any issues related with this are more to do with Xcode's ability to build the [**MetaverseKit**](https://github.com/wabiverse/MetaverseKit) and **SwiftUSD** swift packages, and less to do with swift or anything platform-specific.

I have addressed one of these Xcode errors with this [workaround](https://github.com/wabiverse/MetaverseVulkanFramework/commit/d81c5b35576887a5e04211657cca1535b43ab0a5) related to Xcode's inability to build swift packages that depend on (more than one) **.xcframework** that contain a `module.modulemap` file to it's headers.

Will continue to update this issue with any more relevant findings.

**Comment by furby-tm** [comment]
I have addressed another Xcode error with this [workaround](https://github.com/wabiverse/MetaverseKit/commit/35be6bb25945346031f15f1d6e44e347e9318070) for Xcode's inability to build a target that does not provide object files, because its tooling is hardcoded to expect the output of at least some symbols for all libraries.

The fix for that has been included in [v23.11.3](https://github.com/wabiverse/SwiftUSD/releases/tag/v23.11.3), so be sure to have it pinned as the version minimum for the SwiftUSD dependency within your own project's Package.swift file or Xcode dependencies if your aim is to build with Xcode.

**Comment by furby-tm** [comment]
I can confirm that after the above two workarounds, that **Xcode** is successfully able to build **SwiftUSD** on **macOS**, I will target the other platforms (**iOS** & **visionOS**) and fix any issues as they arise.

Will continue to update this issue with any more relevant findings.

**Comment by furby-tm** [comment]
**iOS** is now supported & [tested](https://github.com/wabiverse/SwiftUSD/issues/5). You can grab it in the latest [release](https://github.com/wabiverse/SwiftUSD/releases/tag/v23.11.21), still need to fixup **visionOS's** python, but **iOS** is complete, update your swift project to include this latest release accordingly:

```swift
dependencies: [
  .package(url: "https://github.com/wabiverse/SwiftUSD.git", from: "23.11.21"),
]
```

Enjoy 🎉 .

**Comment by SimonBenAnderson** [comment]
@furby-tm Thank you so much! I cant wait to give this a go. Sorry about the late reply.
